[build]
  publish = "target/"
  command = "./mvnw clean package -DskipTests"

[build.environment]
  JAVA_VERSION = "21"
  MAVEN_OPTS = "-Xmx1024m"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  DB_URL = "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
  DB_DRIVER = "org.h2.Driver"
  DB_USER = "sa"
  DB_PASS = ""
  FLYWAY_ENABLED = "false"
  JPA_DDL_AUTO = "create-drop"
  HIBERNATE_DIALECT = "org.hibernate.dialect.H2Dialect"
